### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by fr54nk** [aryanvikash/Google-Drive-Uploader#1]
Hello, I tried running the code to start the bot on an ubuntu server but it kept returning the following error. Have you any idea on how to fix it?

 `  File "bot.py", line 49
    drive: GoogleDrive
SyntaxError: invalid syntax`

![shark](https://user-images.githubusercontent.com/35030185/74854058-d3d9a780-534f-11ea-8bef-4b9f4e5bb2d0.png)

**Comment by aryanvikash** [comment]
Did You installed Dependencies ? Using `sudo pip3 install -r requirements.txt `  before  running  bot

**Comment by fr54nk** [comment]
I've just tried running the bot from scratch on a new system and installed the necessary requirements including the command `sudo pip3 install -r requirements.txt` but I still get the same error for some reason. Currently still trying to figure out what could be the problem

**Comment by aryanvikash** [comment]
can you pm me on telegram  @aryanvikash

**Comment by fr54nk** [comment]
Sure thing. Sending you a pm right now

**Comment by aryanvikash** [comment]
So That was Due To Python Version  Use Python3 >= 3.6
