### ISSUE TITLE
"Silly" question :

### ISSUE THREAD

**Issue by Mr-RobotX** [aryanvikash/Google-Drive-Uploader#10]
What is the difference if I configure my own bot as you say at startup?  

PS: What is the "Bot Root Directroy".

**Comment by aryanvikash** [comment]
Difference  ?

Root bot directory  means  inside bot Folder

**Comment by Mr-RobotX** [comment]
Does the bot still work?

**Comment by aryanvikash** [comment]
Yes it works

**Comment by Mr-RobotX** [comment]
You in the publication say:

 "Setup Your Own Bot"
 1. Create Your [Google Drive api Credential] (https://console.cloud.google.com/apis/credentials) (other type) and Download Its json
 2. Paste it In Bot Root Directroy and Rename it "client_secrets.json"
 3. Replace Your Bot Token in [creds.py file] (./ creds.py)
 4. Your Bot is Ready to Host.  "

 What would be the difference if I do that?

**Comment by aryanvikash** [comment]
Actually that source code is for your own bot .. you have to do this If you wanna deploy your own bot . There is no second option . To compare.

**Comment by Mr-RobotX** [comment]
So is it to implement a bot created by me, your bot? EXCUSE ME IF I ASK ANY FOOLISH QUESTIONS, BUT I'M NEW IN ALL OF THIS

**Comment by aryanvikash** [comment]
Everything will be yours . There is nothing mine .  Generate token replace , config bot  and deploy it

**Comment by Mr-RobotX** [comment]
Ok
