### ISSUE TITLE
How can i deploy it to heroku ?

### ISSUE THREAD

**Issue by Suyashjain05** [aryanvikash/Google-Drive-Uploader#4]

**Comment by askfriends** [comment]
yes..it would be nice if you list all steps and deploy to heroku button in readme

**Comment by Suyashjain05** [comment]
oops , didn't notice this issue is still open.
thank you

**Comment by Cool69-69** [comment]
> oops , didn't notice this issue is still open.
> thank you

Do u got an process to do so?
